# Generated by Django 3.2.8 on 2021-11-17 00:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
